# Install script for directory: /home/dida/Desktop/OpneCV/opencv/sources/modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/video/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/cudalegacy/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/python/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/world/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/core/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/calib3d/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/cudawarping/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/cudaimgproc/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/highgui/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/cudafeatures2d/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/cudacodec/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/java/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/cudafilters/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/ts/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/objdetect/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/cudastereo/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/imgcodecs/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/ml/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/features2d/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/cudev/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/cudaarithm/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/stitching/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/photo/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/imgproc/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/cudaobjdetect/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/js/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/superres/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/shape/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/flann/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/viz/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/cudaoptflow/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/cudabgsegm/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/videostab/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/dnn/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/.firstpass/videoio/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/core/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/flann/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/imgproc/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/java_bindings_generator/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/ml/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/objdetect/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/photo/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/video/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/dnn/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/imgcodecs/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/shape/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/videoio/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/highgui/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/superres/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/ts/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/features2d/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/calib3d/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/stitching/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/videostab/cmake_install.cmake")
  include("/home/dida/Desktop/OpneCV/opencv/modules/python_bindings_generator/cmake_install.cmake")

endif()

